---
name: Docker

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    paths-ignore:
      - '*.md'
  release:
    types:
      - published

jobs:
  Hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
        with:
          dockerfile: Dockerfile
  Build:
    runs-on: ubuntu-latest
    needs: Hadolint
    steps:
      - uses: actions/checkout@v2
      - name: Build Dockerfile
        run: docker build .
      - name: Push to GitHub Packages
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v1
        with:
          add_git_labels: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: fx31337/fx-data-convert-action/fx-data-convert-action
          tag_with_ref: true
