---
name: Lint
on:
  - pull_request
  - push
jobs:
  Dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
        with:
          dockerfile: Dockerfile
  Markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: ".markdownlint.yml"
  YAML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: YAML check (yamllint)
        uses: ibiqlik/action-yamllint@master
        with:
          strict: true
  Python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.4
          architecture: x64
      - name: Install Flake
        run: pip install Flake8
      - name: Run Flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          # Note: This needs to be the same as the job name.
          checkName: 'Python'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
